name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 17"
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme XCConfig -destination "${{ matrix.destination }}" test | xcbeautify --renderer github-actions

  linux_test:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - run: mise run test
